# Generated by Django 4.1.5 on 2023-01-30 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("log_reg_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wish",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("granted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishes_uploaded",
                        to="log_reg_app.user",
                    ),
                ),
                (
                    "users_who_like",
                    models.ManyToManyField(
                        related_name="liked_wishes", to="log_reg_app.user"
                    ),
                ),
            ],
        ),
    ]
